-- SSA Oracle XE fresh schema
-- Run this file while connected as the application schema owner.
-- It intentionally contains no schema prefix, tablespace, storage, or export options.
-- Data is supplied by 03_seed_system.sql after 02_sequences.sql.

CREATE TABLE MEMBER (
    MEMBER_ID       VARCHAR2(50 CHAR) NOT NULL,
    NAME            VARCHAR2(50 CHAR) NOT NULL,
    DEPARTMENT      VARCHAR2(20 CHAR) NOT NULL,
    PASSWORD        VARCHAR2(100 CHAR) NOT NULL,
    STATUS          VARCHAR2(1 CHAR) DEFAULT '0' NOT NULL,
    FAIL_COUNT      NUMBER(10) DEFAULT 0 NOT NULL,
    PWD_CHG_DATE    DATE DEFAULT SYSDATE NOT NULL,
    LAST_LONG_DATE  DATE,
    REG_DATE        DATE DEFAULT SYSDATE NOT NULL,
    PHONE           VARCHAR2(100 CHAR),
    EMAIL           VARCHAR2(300 CHAR) NOT NULL,
    PICTURE         VARCHAR2(200 CHAR) DEFAULT 'noImage.jpg' NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT CK_MEMBER_STATUS CHECK (STATUS IN ('0', '1', '2')),
    CONSTRAINT CK_MEMBER_FAIL_COUNT CHECK (FAIL_COUNT >= 0)
);
COMMENT ON TABLE MEMBER IS '사용자 계정';

CREATE TABLE MEMBER_ROLE (
    ROLE_ID     NUMBER(10) NOT NULL,
    ROLE_CODE   VARCHAR2(30 CHAR) DEFAULT 'ROLE_GUEST' NOT NULL,
    MEMBER_ID   VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT PK_MEMBER_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UQ_MEMBER_ROLE UNIQUE (MEMBER_ID, ROLE_CODE),
    CONSTRAINT FK_MEMBER_ROLE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_MEMBER_ROLE_CODE CHECK (ROLE_CODE IN ('ROLE_ADMIN', 'ROLE_USER', 'ROLE_GUEST'))
);
COMMENT ON TABLE MEMBER_ROLE IS '사용자 권한';

CREATE TABLE MEMBER_LOG (
    LOG_ID        NUMBER(10) NOT NULL,
    LOGIN_IP      VARCHAR2(50 CHAR),
    LOGIN_STATUS  VARCHAR2(20 CHAR) NOT NULL,
    LOGIN_DATE    DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_ID     VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT PK_MEMBER_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_MEMBER_LOG_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);
COMMENT ON TABLE MEMBER_LOG IS '로그인 이력';

CREATE TABLE COMMON_CODE (
    GRP_CODE    VARCHAR2(50 CHAR) NOT NULL,
    CODE        VARCHAR2(50 CHAR) NOT NULL,
    CODE_NAME   VARCHAR2(100 CHAR) NOT NULL,
    SORT_SEQ    NUMBER(10) DEFAULT 0 NOT NULL,
    USE_YN      VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    CODE_DATE   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COMMON_CODE PRIMARY KEY (GRP_CODE, CODE),
    CONSTRAINT CK_COMMON_CODE_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_COMMON_CODE_SORT_SEQ CHECK (SORT_SEQ >= 0)
);
COMMENT ON TABLE COMMON_CODE IS '시스템 공통 코드';

CREATE TABLE DANGER_DETAIL (
    DANGER_ID    NUMBER(10) NOT NULL,
    DANGER_NAME  VARCHAR2(100 CHAR) NOT NULL,
    DANGER_DATE  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_DANGER_DETAIL PRIMARY KEY (DANGER_ID),
    CONSTRAINT UQ_DANGER_DETAIL_NAME UNIQUE (DANGER_NAME)
);
COMMENT ON TABLE DANGER_DETAIL IS '위험 객체 마스터';

CREATE TABLE ANIMAL_DETAIL (
    ANIMAL_ID       NUMBER(10) NOT NULL,
    ANIMAL_TYPE     VARCHAR2(10 CHAR) NOT NULL,
    ANIMAL_BREED    VARCHAR2(100 CHAR) NOT NULL,
    ANIMAL_NAME     VARCHAR2(100 CHAR) NOT NULL,
    ENTRANCE_DATE   DATE DEFAULT SYSDATE NOT NULL,
    ANIMAL_STATUS   VARCHAR2(1 CHAR) DEFAULT '0' NOT NULL,
    ANIMAL_PICTURE  VARCHAR2(200 CHAR) DEFAULT 'noImage.jpg' NOT NULL,
    CONSTRAINT PK_ANIMAL_DETAIL PRIMARY KEY (ANIMAL_ID),
    CONSTRAINT CK_ANIMAL_DETAIL_TYPE CHECK (ANIMAL_TYPE IN ('0', '1')),
    CONSTRAINT CK_ANIMAL_DETAIL_STATUS CHECK (ANIMAL_STATUS IN ('0', '1', '2'))
);
COMMENT ON TABLE ANIMAL_DETAIL IS '보호 동물 관리';

CREATE TABLE ANIMAL_COUNTER (
    COUNTER_ID     NUMBER(10) NOT NULL,
    CURRENT_COUNT  NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_UPDATE    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ANIMAL_COUNTER PRIMARY KEY (COUNTER_ID),
    CONSTRAINT CK_ANIMAL_COUNTER_COUNT CHECK (CURRENT_COUNT >= 0)
);
COMMENT ON TABLE ANIMAL_COUNTER IS '보호중 동물 종류별 기준 마릿수';

CREATE TABLE DRONE (
    DRONE_ID           VARCHAR2(30 CHAR) NOT NULL,
    MEMBER_ID          VARCHAR2(50 CHAR),
    CAMERA             VARCHAR2(100 CHAR),
    BATTERY_CAPACITY   NUMBER(10),
    DRONE_LENGTH       NUMBER(10,2),
    DRONE_WIDTH        NUMBER(10,2),
    BRAND              VARCHAR2(100 CHAR),
    MAINTENANCE_COUNT  NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DRONE PRIMARY KEY (DRONE_ID),
    CONSTRAINT FK_DRONE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_DRONE_BATTERY_CAPACITY CHECK (BATTERY_CAPACITY IS NULL OR BATTERY_CAPACITY >= 0),
    CONSTRAINT CK_DRONE_MAINTENANCE CHECK (MAINTENANCE_COUNT >= 0)
);
COMMENT ON TABLE DRONE IS '드론 기체 정보';

CREATE TABLE VIDEO_DRONE_MAP (
    SOURCE_KEY  VARCHAR2(50 CHAR) NOT NULL,
    DRONE_ID    VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT PK_VIDEO_DRONE_MAP PRIMARY KEY (SOURCE_KEY),
    CONSTRAINT FK_VIDEO_DRONE_MAP_DRONE FOREIGN KEY (DRONE_ID) REFERENCES DRONE (DRONE_ID)
);
COMMENT ON TABLE VIDEO_DRONE_MAP IS '영상 소스와 드론 매핑';

CREATE TABLE FLIGHT_HISTORY (
    FLIGHT_ID                NUMBER(10) NOT NULL,
    START_TIME               TIMESTAMP NOT NULL,
    END_TIME                 TIMESTAMP NOT NULL,
    FLIGHT_DURATION          NUMBER(12,2) DEFAULT 0 NOT NULL,
    START_BATTERY_PERCENT    NUMBER(5,2),
    END_BATTERY_PERCENT      NUMBER(5,2),
    BATTERY_CONSUMPTION      NUMBER(5,2),
    FLIGHT_DATE              DATE DEFAULT SYSDATE NOT NULL,
    DRONE_ID                 VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT PK_FLIGHT_HISTORY PRIMARY KEY (FLIGHT_ID),
    CONSTRAINT FK_FLIGHT_HISTORY_DRONE FOREIGN KEY (DRONE_ID) REFERENCES DRONE (DRONE_ID),
    CONSTRAINT CK_FLIGHT_HISTORY_DURATION CHECK (FLIGHT_DURATION >= 0),
    CONSTRAINT CK_FLIGHT_HISTORY_START_BATTERY CHECK (START_BATTERY_PERCENT IS NULL OR START_BATTERY_PERCENT BETWEEN 0 AND 100),
    CONSTRAINT CK_FLIGHT_HISTORY_END_BATTERY CHECK (END_BATTERY_PERCENT IS NULL OR END_BATTERY_PERCENT BETWEEN 0 AND 100),
    CONSTRAINT CK_FLIGHT_HISTORY_CONSUMPTION CHECK (BATTERY_CONSUMPTION IS NULL OR BATTERY_CONSUMPTION BETWEEN 0 AND 100)
);
COMMENT ON TABLE FLIGHT_HISTORY IS '드론 비행 이력';

CREATE TABLE DETECTION_LOG (
    DLOG_ID          NUMBER(10) NOT NULL,
    DETECT_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ANIMAL_TYPE      VARCHAR2(10 CHAR) NOT NULL,
    SNAPSHOT_PATH    VARCHAR2(1000 CHAR) DEFAULT 'NONE' NOT NULL,
    DETECTION_DATE   DATE DEFAULT SYSDATE NOT NULL,
    DRONE_ID         VARCHAR2(30 CHAR) NOT NULL,
    ACTION_STATUS    VARCHAR2(1 CHAR) DEFAULT '0' NOT NULL,
    ACTION_REASON    VARCHAR2(1000 CHAR),
    DETECT_COUNT     NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DETECTION_LOG PRIMARY KEY (DLOG_ID),
    CONSTRAINT FK_DETECTION_LOG_DRONE FOREIGN KEY (DRONE_ID) REFERENCES DRONE (DRONE_ID),
    CONSTRAINT CK_DETECTION_LOG_ANIMAL_TYPE CHECK (ANIMAL_TYPE IN ('0', '1')),
    CONSTRAINT CK_DETECTION_LOG_ACTION CHECK (ACTION_STATUS IN ('0', '1', '2')),
    CONSTRAINT CK_DETECTION_LOG_COUNT CHECK (DETECT_COUNT >= 0)
);
COMMENT ON TABLE DETECTION_LOG IS '동물 미달 탐지 이력';

CREATE TABLE DANGER_LOG (
    DANLOG_ID        NUMBER(10) NOT NULL,
    DANGER_TYPE      NUMBER(10) NOT NULL,
    DANGER_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DACTION_STATUS   VARCHAR2(1 CHAR) DEFAULT '0' NOT NULL,
    DACTION_REASON   VARCHAR2(1000 CHAR),
    DSNAPSHOT_PATH   VARCHAR2(1000 CHAR) DEFAULT 'NONE' NOT NULL,
    DANGER_DATE      DATE DEFAULT SYSDATE NOT NULL,
    DRONE_ID         VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT PK_DANGER_LOG PRIMARY KEY (DANLOG_ID),
    CONSTRAINT FK_DANGER_LOG_DRONE FOREIGN KEY (DRONE_ID) REFERENCES DRONE (DRONE_ID),
    CONSTRAINT CK_DANGER_LOG_TYPE CHECK (DANGER_TYPE IN (2, 3, 4, 5)),
    CONSTRAINT CK_DANGER_LOG_ACTION CHECK (DACTION_STATUS IN ('0', '1', '2'))
);
COMMENT ON TABLE DANGER_LOG IS '위험 객체 탐지 이력';

CREATE TABLE ALERT_LOG (
    ALERT_ID          NUMBER(10) NOT NULL,
    ALERT_TYPE        VARCHAR2(20 CHAR) NOT NULL,
    DLOG_ID           NUMBER(10),
    DANLOG_ID         NUMBER(10),
    ALERT_MSG         VARCHAR2(1000 CHAR) NOT NULL,
    SEND_STATUS       VARCHAR2(20 CHAR) NOT NULL,
    SEND_DATE         DATE DEFAULT SYSDATE NOT NULL,
    FIRST_SEND_TIME   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERT_LOG PRIMARY KEY (ALERT_ID),
    CONSTRAINT FK_ALERT_LOG_DETECTION FOREIGN KEY (DLOG_ID) REFERENCES DETECTION_LOG (DLOG_ID),
    CONSTRAINT FK_ALERT_LOG_DANGER FOREIGN KEY (DANLOG_ID) REFERENCES DANGER_LOG (DANLOG_ID),
    CONSTRAINT CK_ALERT_LOG_TYPE CHECK (ALERT_TYPE IN ('0', '1')),
    CONSTRAINT CK_ALERT_LOG_SEND_STATUS CHECK (SEND_STATUS IN ('0', '1', '성공', '실패'))
);
COMMENT ON TABLE ALERT_LOG IS '경보 발송 이력';

CREATE TABLE ENVIRONMENT (
    ENVIRONMENT_ID  NUMBER(10) NOT NULL,
    LOCATION_NAME   VARCHAR2(100 CHAR) NOT NULL,
    ADDRESS         VARCHAR2(300 CHAR) NOT NULL,
    LATITUDE        NUMBER(10,6) NOT NULL,
    LONGITUDE       NUMBER(10,6) NOT NULL,
    TIMEZONE        VARCHAR2(50 CHAR) DEFAULT 'Asia/Seoul' NOT NULL,
    USE_YN          VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    UPDATE_DATE     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ENVIRONMENT PRIMARY KEY (ENVIRONMENT_ID),
    CONSTRAINT CK_ENVIRONMENT_LATITUDE CHECK (LATITUDE BETWEEN -90 AND 90),
    CONSTRAINT CK_ENVIRONMENT_LONGITUDE CHECK (LONGITUDE BETWEEN -180 AND 180),
    CONSTRAINT CK_ENVIRONMENT_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);
COMMENT ON TABLE ENVIRONMENT IS '관제 환경 위치 설정';

CREATE TABLE ALERT_POLICY (
    POLICY_KEY            VARCHAR2(50 CHAR) NOT NULL,
    UNDER_TARGET_SECONDS  NUMBER(6,2) NOT NULL,
    UPDATED_BY            VARCHAR2(50 CHAR) NOT NULL,
    UPDATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERT_POLICY PRIMARY KEY (POLICY_KEY),
    CONSTRAINT CK_ALERT_POLICY_DURATION CHECK (UNDER_TARGET_SECONDS BETWEEN 1 AND 3600)
);
COMMENT ON TABLE ALERT_POLICY IS '경보 정책 설정';

CREATE TABLE ALERT_MESSAGE_TEMPLATE (
    TEMPLATE_KEY   VARCHAR2(50 CHAR) NOT NULL,
    TEMPLATE_NAME  VARCHAR2(100 CHAR) NOT NULL,
    TEMPLATE_TEXT  VARCHAR2(1000 CHAR) NOT NULL,
    UPDATED_BY     VARCHAR2(50 CHAR),
    UPDATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERT_MESSAGE_TEMPLATE PRIMARY KEY (TEMPLATE_KEY)
);
COMMENT ON TABLE ALERT_MESSAGE_TEMPLATE IS '경보 문구 템플릿';

CREATE TABLE PATROL_REPORT (
    REPORT_ID           NUMBER(10) NOT NULL,
    REPORT_DATE         DATE NOT NULL,
    TOTAL_FLIGHT_TIME   NUMBER(12,2) DEFAULT 0 NOT NULL,
    TOTAL_DETECT_COUNT  NUMBER(10) DEFAULT 0 NOT NULL,
    COMPLETION_RATE     NUMBER(6,2) DEFAULT 0 NOT NULL,
    CONFIRM_STATUS      VARCHAR2(1 CHAR) DEFAULT '0' NOT NULL,
    PATROL_DATE         DATE NOT NULL,
    MOD_DATE            TIMESTAMP,
    MEMBER_ID           VARCHAR2(50 CHAR) NOT NULL,
    ACTION_TAKEN        VARCHAR2(4000 BYTE),
    REMARK              VARCHAR2(4000 BYTE),
    CONSTRAINT PK_PATROL_REPORT PRIMARY KEY (REPORT_ID),
    CONSTRAINT FK_PATROL_REPORT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_PATROL_REPORT_TIME CHECK (TOTAL_FLIGHT_TIME >= 0),
    CONSTRAINT CK_PATROL_REPORT_COUNT CHECK (TOTAL_DETECT_COUNT >= 0),
    CONSTRAINT CK_PATROL_REPORT_RATE CHECK (COMPLETION_RATE BETWEEN 0 AND 100),
    CONSTRAINT CK_PATROL_REPORT_CONFIRM CHECK (CONFIRM_STATUS IN ('0', '1', '2'))
);
COMMENT ON TABLE PATROL_REPORT IS '일일 관제 업무 보고서';

CREATE TABLE PDF_CACHE (
    PDF_CACHE_ID        NUMBER(10) NOT NULL,
    PDF_FILE_PATH       VARCHAR2(1000 CHAR),
    GENERATION_STATUS   VARCHAR2(20 CHAR) NOT NULL,
    PDF_DATE            DATE DEFAULT SYSDATE NOT NULL,
    REPORT_ID           NUMBER(10) NOT NULL,
    CONSTRAINT PK_PDF_CACHE PRIMARY KEY (PDF_CACHE_ID),
    CONSTRAINT FK_PDF_CACHE_REPORT FOREIGN KEY (REPORT_ID) REFERENCES PATROL_REPORT (REPORT_ID),
    CONSTRAINT CK_PDF_CACHE_STATUS CHECK (GENERATION_STATUS IN ('REQUEST', 'SUCCESS', 'FAIL'))
);
COMMENT ON TABLE PDF_CACHE IS '보고서 PDF 생성 캐시';

CREATE TABLE WORKFLOW (
    APPROVAL_ID    NUMBER(10) NOT NULL,
    APP_STATUS     VARCHAR2(1 CHAR) DEFAULT '0' NOT NULL,
    REJECT_REASON  VARCHAR2(1000 CHAR),
    ADMIN_SIGN     VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    REQUEST_DATE   DATE DEFAULT SYSDATE NOT NULL,
    COMPLETE_DATE  DATE,
    DRAFTER_ID     VARCHAR2(50 CHAR) NOT NULL,
    APPROVER_ID    VARCHAR2(50 CHAR) NOT NULL,
    REPORT_ID      NUMBER(10) NOT NULL,
    CONSTRAINT PK_WORKFLOW PRIMARY KEY (APPROVAL_ID),
    CONSTRAINT FK_WORKFLOW_DRAFTER FOREIGN KEY (DRAFTER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_WORKFLOW_APPROVER FOREIGN KEY (APPROVER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_WORKFLOW_REPORT FOREIGN KEY (REPORT_ID) REFERENCES PATROL_REPORT (REPORT_ID),
    CONSTRAINT CK_WORKFLOW_STATUS CHECK (APP_STATUS IN ('0', '1', '2')),
    CONSTRAINT CK_WORKFLOW_SIGN CHECK (ADMIN_SIGN IN ('Y', 'N'))
);
COMMENT ON TABLE WORKFLOW IS '보고서 결재 이력';

-- Supporting indexes for current list/detail mappers.
CREATE INDEX IX_MEMBER_LOG_MEMBER_DATE ON MEMBER_LOG (MEMBER_ID, LOGIN_DATE);
CREATE INDEX IX_DETECTION_LOG_DRONE_DATE ON DETECTION_LOG (DRONE_ID, DETECTION_DATE);
CREATE INDEX IX_DANGER_LOG_DRONE_DATE ON DANGER_LOG (DRONE_ID, DANGER_DATE);
CREATE INDEX IX_FLIGHT_HISTORY_DRONE_DATE ON FLIGHT_HISTORY (DRONE_ID, FLIGHT_DATE);
CREATE INDEX IX_ALERT_LOG_SEND_DATE ON ALERT_LOG (SEND_DATE);
CREATE INDEX IX_PATROL_REPORT_MEMBER ON PATROL_REPORT (MEMBER_ID);
CREATE INDEX IX_WORKFLOW_APPROVER ON WORKFLOW (APPROVER_ID, APP_STATUS);
