-- SSA minimum development seed data
-- Run after 01_schema.sql and 02_sequences.sql.
-- This file has no production data, real accounts, upload paths, API keys, or device URLs.
SET DEFINE OFF;

-- ---------------------------------------------------------------------------
-- 1. Required common codes used by current controllers, JSPs, and YOLO bridge
-- ---------------------------------------------------------------------------
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ACCOUNT_STATUS', '0', '정상', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ACCOUNT_STATUS', '1', '정지', 2, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ACCOUNT_STATUS', '2', '휴면', 3, 'Y', SYSDATE);

INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('USER_ROLE', 'ROLE_ADMIN', '관리자', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('USER_ROLE', 'ROLE_USER', '관제원', 2, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('USER_ROLE', 'ROLE_GUEST', '미인가', 3, 'Y', SYSDATE);

INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ANIMAL_TYPE', '0', '개', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ANIMAL_TYPE', '1', '고양이', 2, 'Y', SYSDATE);

-- Flask YOLO_TO_CODE: blue_alien=2, blue_shark=3, pink_dragon=4, tiger=5.
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('DANGER_TYPE', '2', '외계인', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('DANGER_TYPE', '3', '상어', 2, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('DANGER_TYPE', '4', '용', 3, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('DANGER_TYPE', '5', '호랑이', 4, 'Y', SYSDATE);

INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('SEND_STATUS', '0', '실패', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('SEND_STATUS', '1', '성공', 2, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ALERT_TYPE', '0', '동물미달', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ALERT_TYPE', '1', '이상개체', 2, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('CONFIRM_STATUS', '0', '승인 대기', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('CONFIRM_STATUS', '1', '승인 완료', 2, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('CONFIRM_STATUS', '2', '반려', 3, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ACTION_STATUS', '0', '미확인', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ACTION_STATUS', '1', '조치중', 2, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ACTION_STATUS', '2', '조치완료', 3, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ANIMAL_STATUS', '0', '보호중', 1, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ANIMAL_STATUS', '1', '입양', 2, 'Y', SYSDATE);
INSERT INTO COMMON_CODE (GRP_CODE, CODE, CODE_NAME, SORT_SEQ, USE_YN, CODE_DATE) VALUES ('ANIMAL_STATUS', '2', '퇴소', 3, 'Y', SYSDATE);

-- ---------------------------------------------------------------------------
-- 2. Default development administrator
--    Login: admin / ssa1234!  (replace before any shared deployment)
-- ---------------------------------------------------------------------------
INSERT INTO MEMBER (
    MEMBER_ID, NAME, DEPARTMENT, PASSWORD, STATUS, FAIL_COUNT,
    PWD_CHG_DATE, LAST_LONG_DATE, REG_DATE, PHONE, EMAIL, PICTURE
) VALUES (
    'admin', 'Administrator', 'System Administration',
    '$2a$10$K7Ic0rIfCIedmCfpMZnz.OHsoGJ4xahBSpltndmTKfhdoBw1p6yHm',
    '0', 0, SYSDATE, NULL, SYSDATE, '010-0000-0000', 'admin@example.com', 'noImage.jpg'
);
-- MEMBER_ROLE uses MAX(ROLE_ID)+1 in the current Mapper, so no sequence is created.
INSERT INTO MEMBER_ROLE (ROLE_ID, ROLE_CODE, MEMBER_ID) VALUES (1, 'ROLE_ADMIN', 'admin');

-- ---------------------------------------------------------------------------
-- 3. YOLO danger master and safe sample shelter inventory
-- ---------------------------------------------------------------------------
INSERT INTO DANGER_DETAIL (DANGER_ID, DANGER_NAME, DANGER_DATE) VALUES (2, '외계인', SYSDATE);
INSERT INTO DANGER_DETAIL (DANGER_ID, DANGER_NAME, DANGER_DATE) VALUES (3, '상어', SYSDATE);
INSERT INTO DANGER_DETAIL (DANGER_ID, DANGER_NAME, DANGER_DATE) VALUES (4, '용', SYSDATE);
INSERT INTO DANGER_DETAIL (DANGER_ID, DANGER_NAME, DANGER_DATE) VALUES (5, '호랑이', SYSDATE);

-- noImage.jpg is the application fallback asset; no uploaded image names are seeded.
INSERT INTO ANIMAL_DETAIL (ANIMAL_ID, ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_NAME, ENTRANCE_DATE, ANIMAL_STATUS, ANIMAL_PICTURE) VALUES (1, '0', '진돗개', '루루', TRUNC(SYSDATE), '0', 'noImage.jpg');
INSERT INTO ANIMAL_DETAIL (ANIMAL_ID, ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_NAME, ENTRANCE_DATE, ANIMAL_STATUS, ANIMAL_PICTURE) VALUES (2, '0', '푸들', '치치', TRUNC(SYSDATE), '0', 'noImage.jpg');
INSERT INTO ANIMAL_DETAIL (ANIMAL_ID, ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_NAME, ENTRANCE_DATE, ANIMAL_STATUS, ANIMAL_PICTURE) VALUES (3, '1', '숏헤어', '단단', TRUNC(SYSDATE), '0', 'noImage.jpg');
INSERT INTO ANIMAL_DETAIL (ANIMAL_ID, ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_NAME, ENTRANCE_DATE, ANIMAL_STATUS, ANIMAL_PICTURE) VALUES (4, '1', '렉돌', '나나', TRUNC(SYSDATE), '1', 'noImage.jpg');
INSERT INTO ANIMAL_DETAIL (ANIMAL_ID, ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_NAME, ENTRANCE_DATE, ANIMAL_STATUS, ANIMAL_PICTURE) VALUES (5, '1', '치즈', '루루', TRUNC(SYSDATE), '2', 'noImage.jpg');
INSERT INTO ANIMAL_DETAIL (ANIMAL_ID, ANIMAL_TYPE, ANIMAL_BREED, ANIMAL_NAME, ENTRANCE_DATE, ANIMAL_STATUS, ANIMAL_PICTURE) VALUES (6, '0', '리트리버', '엔디', TRUNC(SYSDATE), '1', 'noImage.jpg');

-- The count used by shortage detection includes protected animals only (ANIMAL_STATUS = '0').
INSERT INTO ANIMAL_COUNTER (COUNTER_ID, CURRENT_COUNT, LAST_UPDATE) VALUES (0, 2, SYSDATE);
INSERT INTO ANIMAL_COUNTER (COUNTER_ID, CURRENT_COUNT, LAST_UPDATE) VALUES (1, 1, SYSDATE);

-- ---------------------------------------------------------------------------
-- 4. Generic development drone/source setup (no member assignment or device URL)
-- ---------------------------------------------------------------------------
INSERT INTO DRONE (DRONE_ID, MEMBER_ID, CAMERA, BATTERY_CAPACITY, DRONE_LENGTH, DRONE_WIDTH, BRAND, MAINTENANCE_COUNT) VALUES ('DRONE01', NULL, 'CAMERA_1', 5000, 320, 320, 'SSA Sample', 0);
INSERT INTO DRONE (DRONE_ID, MEMBER_ID, CAMERA, BATTERY_CAPACITY, DRONE_LENGTH, DRONE_WIDTH, BRAND, MAINTENANCE_COUNT) VALUES ('DRONE02', NULL, 'CAMERA_2', 5000, 320, 320, 'SSA Sample', 0);
INSERT INTO DRONE (DRONE_ID, MEMBER_ID, CAMERA, BATTERY_CAPACITY, DRONE_LENGTH, DRONE_WIDTH, BRAND, MAINTENANCE_COUNT) VALUES ('DRONE03', NULL, 'CAMERA_3', 5000, 320, 320, 'SSA Sample', 0);
INSERT INTO DRONE (DRONE_ID, MEMBER_ID, CAMERA, BATTERY_CAPACITY, DRONE_LENGTH, DRONE_WIDTH, BRAND, MAINTENANCE_COUNT) VALUES ('DRONE04', NULL, 'ESP32_CAMERA', 5000, 320, 320, 'SSA Sample', 0);
INSERT INTO DRONE (DRONE_ID, MEMBER_ID, CAMERA, BATTERY_CAPACITY, DRONE_LENGTH, DRONE_WIDTH, BRAND, MAINTENANCE_COUNT) VALUES ('DRONE05', NULL, 'CAMERA_5', 5000, 320, 320, 'SSA Sample', 0);

INSERT INTO VIDEO_DRONE_MAP (SOURCE_KEY, DRONE_ID) VALUES ('video_1', 'DRONE01');
INSERT INTO VIDEO_DRONE_MAP (SOURCE_KEY, DRONE_ID) VALUES ('video_2', 'DRONE02');
INSERT INTO VIDEO_DRONE_MAP (SOURCE_KEY, DRONE_ID) VALUES ('video_3', 'DRONE03');
INSERT INTO VIDEO_DRONE_MAP (SOURCE_KEY, DRONE_ID) VALUES ('esp32', 'DRONE04');

-- ---------------------------------------------------------------------------
-- 5. Generic initial environment and alert settings
-- ---------------------------------------------------------------------------
INSERT INTO ENVIRONMENT (
    ENVIRONMENT_ID, LOCATION_NAME, ADDRESS, LATITUDE, LONGITUDE, TIMEZONE, USE_YN, UPDATE_DATE
) VALUES (
    SEQ_ENVIRONMENT.NEXTVAL, 'SSA Test Area', 'Seoul, Republic of Korea',
    37.566500, 126.978000, 'Asia/Seoul', 'Y', SYSDATE
);

INSERT INTO ALERT_POLICY (POLICY_KEY, UNDER_TARGET_SECONDS, UPDATED_BY, UPDATED_AT)
VALUES ('ANIMAL_SHORTAGE', 10, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO ALERT_MESSAGE_TEMPLATE (TEMPLATE_KEY, TEMPLATE_NAME, TEMPLATE_TEXT, UPDATED_BY, UPDATED_AT)
VALUES ('ANIMAL_SHORTAGE', '개체 미달 경보', '관제 구역 내 {animalName} 보유 마리수 기준치 미달 현상 지속 감지!', 'SYSTEM', SYSTIMESTAMP);

INSERT INTO ALERT_MESSAGE_TEMPLATE (TEMPLATE_KEY, TEMPLATE_NAME, TEMPLATE_TEXT, UPDATED_BY, UPDATED_AT)
VALUES ('DANGER_OBJECT', '위험 이상객체 경보', '관제 구역 내 위험 이상객체 [{dangerName}] 실시간 출현! 즉시 대피 요망.', 'SYSTEM', SYSTIMESTAMP);

-- Runtime/history tables intentionally have no seed rows:
-- MEMBER_LOG, DETECTION_LOG, DANGER_LOG, ALERT_LOG, FLIGHT_HISTORY,
-- PATROL_REPORT, PDF_CACHE, WORKFLOW.
COMMIT;
