-- Run once in the SSA Oracle schema before saving the setting from the popup.
-- Existing alert history and alert-message templates are not modified.

CREATE TABLE ALERT_POLICY (
    POLICY_KEY           VARCHAR2(50 CHAR) PRIMARY KEY,
    UNDER_TARGET_SECONDS NUMBER(6,2) NOT NULL,
    UPDATED_BY           VARCHAR2(50 CHAR) NOT NULL,
    UPDATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_ALERT_POLICY_DURATION
        CHECK (UNDER_TARGET_SECONDS BETWEEN 1 AND 3600)
);

INSERT INTO ALERT_POLICY (POLICY_KEY, UNDER_TARGET_SECONDS, UPDATED_BY, UPDATED_AT)
SELECT 'ANIMAL_SHORTAGE', 10, 'SYSTEM', SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM ALERT_POLICY
    WHERE POLICY_KEY = 'ANIMAL_SHORTAGE'
);

COMMIT;
